const express = require('express')
const router = express.Router()
const userController = require('../../controllers/user-controller')
const { authenticated } = require('../../middleware/auth')
const { validate } = require('../../middleware/express-validator')
router.get('/:id/tweets', authenticated, userController.getUser)
router.get('/:id/replies', authenticated, userController.getReplies)
router.get('/:id/likes', authenticated, userController.getLikes)
router.get('/:id/followers', authenticated, userController.getFollowers)
router.get('/:id/followings', authenticated, userController.getFollowings)
router.get('/search', authenticated, userController.searchUser)
router.get('/setting/:id', authenticated, userController.getSetting)
router.put('/setting/:id', authenticated, validate.user, userController.putUser)
module.exports = router
