const express = require('express')
const router = express.Router()
const passport = require('../config/passport')
const { generalErrorHandler } = require('../middleware/error-handler')
const tweet = require('./modules/tweet')
const followship = require('./modules/followship')
const user = require('./modules/user')
const api = require('./modules/api')
const userController = require('../controllers/user-controller')
const { authenticated, antiAuthenticated } = require('../middleware/auth')
const admin = require('./modules/admin')
const message = require('./modules/message')
const { validate } = require('../middleware/express-validator')

router.use('/api', authenticated, api)
router.use('/users', authenticated, user)
router.use('/admin', admin)
router.use('/tweets', authenticated, tweet)
router.use('/followships', followship)
router.get('/signin', antiAuthenticated, userController.signInPage)
router.post('/signin', antiAuthenticated, validate.signin,
  passport.authenticate('local', { failureRedirect: '/signin', failureFlash: true }),
  userController.signIn
)
router.get('/signup', antiAuthenticated, userController.signUpPage)
router.post('/signup', antiAuthenticated, validate.user, userController.signUp)
router.get('/logout', authenticated, userController.logout)
router.use('/messages', authenticated, message)
router.use('/', authenticated, (req, res) => res.redirect('/tweets'))
router.use('/', generalErrorHandler)
module.exports = router
